# TODO: a Deployment that runs 3 replicas of YOUR image; the container serves on port 8080.
# Docs: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clo835-a2-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clo835-a2-app
  template:
    metadata:
      labels:
        app: clo835-a2-app
    spec:
      containers:
        - name: clo835-a2-app
          image: tvu27/clo835-a2:0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5